### ISSUE TITLE
Missing commits

### ISSUE THREAD

**Issue by dcardin** [mgipson/AR-SwiftUI#1]
Hello Madison!
Looked at your article https://medium.com/dev-genius/implementing-ar-in-swiftui-without-storyboards-ec529ace7ab2
came looking for the code but it appears only the base skeleton is there, not the full project.
thanks

**Comment by madisonostermann** [comment]
Hey there!
Thanks for letting me know; I don't know how that got missed!
I uploaded the code for ContentView.swift and ARView.swift; the other files are the same boilerplate template files.

Let me know how it works for you!

**Comment by dcardin** [comment]
Things seem there now. Thanks 👍
